westcos-tool.c:fix memory leaks in dst->modulus.data and dst->exponen…
OpenSC/OpenSC pull request #2132
Opened 2020-10-12 05:44 UTC by whzhe51

…t.data

Signed-off-by: whzhe <wanghongzhe@huawei.com>

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

2020-10-13 12:17 UTC, Jakuje requested changes

2020-10-13 12:17 UTC, Jakuje commented on src/tools/westcos-tool.c
>  		}
`dst->modulus` already leaks if the condition on line 675 fails. It would be worth adding the free there too.

2020-10-13 12:17 UTC, Jakuje commented on src/tools/westcos-tool.c
> +		if(dst->modulus.data)
On line 582, the `key` structure is initialized to zeroes so this condition is bogus. Calling just free should be enough. In the following condition too.

2020-10-14 05:57 UTC, whzhe51 commented
@Jakuje OK，I fixed the mr.

2020-10-14 09:20 UTC, Jakuje approved these changes
lgtm

2020-10-14 21:09 UTC, merged

2020-10-14 21:09 UTC, frankmorgner commented
thanks!