Weekly dose of fixes for issues reported by oss-fuzz
OpenSC/OpenSC pull request #2219
Opened 2021-02-03 20:52 UTC by Jakuje

##### Checklist

- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

2021-02-03 22:05 UTC, vjardin commented
LGTM (code review).

2021-02-04 16:49 UTC, frankmorgner requested changes

2021-02-04 16:49 UTC, frankmorgner commented on src/libopensc/card-cardos.c
>  		if (p == NULL)
`if (pp == NULL)`?

2021-02-04 17:03 UTC, Jakuje commented on src/libopensc/card-cardos.c
>  		if (p == NULL)
Right. Good catch. Will fix.

2021-02-11 10:29 UTC, Jakuje commented
@vjardin I see you working on iasecc now. The top commit is fixing one issue reported by oss-fuzz when the ACLs returns empty zero-length data, there was buffer overflow. Can you check my change is not breaking anything for you?

2021-02-11 11:33 UTC, Jakuje commented
(I bundled up couple of new fixes for coverity too)

2021-02-23 19:54 UTC, Jakuje commented
@frankmorgner did you manage to re-review this PR?

2021-02-25 08:08 UTC, frankmorgner approved these changes

2021-02-25 08:08 UTC, merged