PIV: Fixed detection of PIV AID via empty discovery
OpenSC/OpenSC pull request #2441
Opened 2021-11-11 15:56 UTC by frankmorgner

Since we are using the discovery object to detect whether it's a proper
PIV application, `piv_parse_discovery()` should not return SC_SUCCESS on
empty files or on files with *some* ASN.1 structure... Instead, at least
the encoding of the PIV AID should be strictly according NIST SP 800-73-4

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

2021-11-11 16:15 UTC, dengert commented
This was in #2053

2021-11-11 18:51 UTC, frankmorgner commented
Well, partially. `piv_parse_discovery()` still [returns `SC_SUCCESS` for an empty file](https://github.com/OpenSC/OpenSC/blob/4f60c2fdc1028a45417abbcff8e0b5479356f7b4/src/libopensc/card-piv.c#L4686).

2021-11-18 12:29 UTC, Jakuje requested changes

2021-11-19 17:55 UTC, frankmorgner commented
I'll open a unified draft PR with all simplifications.

2021-11-19 17:55 UTC, closed without merging