cardos: fixed reading file information blocks
OpenSC/OpenSC pull request #2561
Opened 2022-05-26 00:25 UTC by frankmorgner

currently untested

fixes Stack-buffer-overflow READ
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47035

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

2022-06-09 06:54 UTC, Jakuje commented
Sorry for a delay with testing. Just tested with cardos 5.3 card and getting the following error from `opensc-explorer` when asking for the `ls`:
```
P:3021788; T:0x139644277250048 08:43:44.113 [opensc-explorer] card.c:473:sc_lock: called
P:3021788; T:0x139644277250048 08:43:44.113 [opensc-explorer] reader-pcsc.c:688:pcsc_lock: called
P:3021788; T:0x139644277250048 08:43:44.113 [opensc-explorer] card.c:522:sc_lock: returning with: 0 (Success)
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] card.c:568:sc_list_files: called
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] card-cardos.c:503:cardos_list_files: called
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] apdu.c:550:sc_transmit_apdu: called
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] card.c:473:sc_lock: called
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] card.c:522:sc_lock: returning with: 0 (Success)
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] apdu.c:515:sc_transmit: called
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] apdu.c:363:sc_single_transmit: called
P:3021788; T:0x139644277250048 08:43:44.114 [opensc-explorer] apdu.c:367:sc_single_transmit: CLA:80, INS:16, P1:2, P2:0, data(0) (nil)
P:3021788; T:0x139644277250048 08:43:44.115 [opensc-explorer] reader-pcsc.c:325:pcsc_transmit: reader 'OMNIKEY AG CardMan 3121 01 00'
P:3021788; T:0x139644277250048 08:43:44.115 [opensc-explorer] reader-pcsc.c:326:pcsc_transmit: 
Outgoing APDU (5 bytes):
80 16 02 00 00 .....

P:3021788; T:0x139644277250048 08:43:44.115 [opensc-explorer] reader-pcsc.c:244:pcsc_internal_transmit: called
P:3021788; T:0x139644277250048 08:43:44.122 [opensc-explorer] reader-pcsc.c:335:pcsc_transmit: 
Incoming APDU (30 bytes):
6F 0C 82 01 04 86 02 2F 10 C2 03 04 06 CA 6F 0C o....../......o.
82 01 38 86 02 50 15 C2 03 04 07 BB 90 00       ..8..P........

P:3021788; T:0x139644277250048 08:43:44.122 [opensc-explorer] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:3021788; T:0x139644277250048 08:43:44.123 [opensc-explorer] apdu.c:539:sc_transmit: returning with: 0 (Success)
P:3021788; T:0x139644277250048 08:43:44.123 [opensc-explorer] card.c:532:sc_unlock: called
P:3021788; T:0x139644277250048 08:43:44.123 [opensc-explorer] card-cardos.c:530:cardos_list_files: directory tag missing
P:3021788; T:0x139644277250048 08:43:44.123 [opensc-explorer] card.c:574:sc_list_files: returning with: -1400 (Internal error)
P:3021788; T:0x139644277250048 08:43:44.123 [opensc-explorer] card.c:532:sc_unlock: called
P:3021788; T:0x139644277250048 08:43:44.123 [opensc-explorer] reader-pcsc.c:740:pcsc_unlock: called
Unable to receive file listing: Internal error
```
On the same card with OpenSC 0.22.0 it works as expected (as well as without your commit):
```
[jjelen@t490s oss-fuzz (podman)]$ opensc-explorer 
OpenSC Explorer version 0.22.0
Using reader with a card: OMNIKEY AG CardMan 3121 01 00
unable to change lifecycle: Security status not satisfied
OpenSC [3F00]> ls
FileID	Type  Size
 2F10 	 wEF    88
[5015]	  DF 26253	Name: \xA0\x00\x00\x00cPKCS-15
```
Did not get back to check if either of the values are somehow behind the buffers though. Valgrind does not complain

2022-06-14 17:13 UTC, Jakuje requested changes

2022-06-14 17:13 UTC, Jakuje commented on src/libopensc/card-cardos.c
> +		len -= tlen - (tag - p);
this is the problem. This lines evaluates to `len = len - (tlen - (tag - p));`, while we want `len = (len - tlen) - (tag - p);`. Fixing this makes the cardos card working here again. I would suggest to rewrite it for readability like this:
```suggestion
		len = len - tlen - (tag - p);
```

2022-06-20 10:19 UTC, Jakuje approved these changes

2022-06-20 10:33 UTC, frankmorgner commented
thank you

2022-06-20 10:33 UTC, merged