enable use_file_cache for MyEID card
OpenSC/OpenSC pull request #2798
Opened 2023-06-08 08:15 UTC by popovec

This PR implements new card_ctl (SC_CARDCTL_GET_CHANGE_COUNTER) which makes it possible to identify every change on the card. This information allows us to safely use the file cache even if the contents of the card is changed on another computer. In this PR, this operation is implemented for the MyEID driver and the file cache for the MyEID card is turned on by default.

##### Checklist
- [x] Documentation is added or updated
- [x] PKCS#11 module is tested

2023-06-09 12:53 UTC, frankmorgner requested changes

2023-06-09 12:53 UTC, frankmorgner commented on src/libopensc/types.h
> +typedef int sc_change_counter;
I think this typedef is a little too much. Just using a size_t to reflect the state would be enough, I think.

2023-06-12 11:14 UTC, popovec commented
Ok "size_t" is perfectly sufficient.

2023-06-23 20:40 UTC, frankmorgner approved these changes
looks good, thank you

2023-06-28 10:11 UTC, merged