Add support for D-Trust Card 5.1 & 5.4
OpenSC/OpenSC pull request #3137
Opened 2024-05-08 20:02 UTC by hamarituc

This is a work in progress effort to support D-Trust Cards 5.1 & 5.4 (see #3131). There is still a lot to do.

* [ ] Query Card Access Number (CAN)
* [ ] Cache CAN
* [ ] Establish PACE channel
* [ ] Implement card initialization in `dtrust-tool`

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

2025-01-29 07:41 UTC, frankmorgner requested changes
The code looks very promising. Apart from the comments above, here are some general suggestions:

- Did you test caching of CAN in Windows Edge/IE? Last time I used this trick (I only have experience with IE), the browser was executed in a temporary user account, which had a different (temporary) home directory, which in turn is used by the PKCS#15 layer for caching files. I'm not sure if this security measure (?) is used by default or if it is triggered by some GPO, nor am I sure whether it is also used for Edge. When I ran into this problem I tied the caching directory to some path that was globally readable/writable. In less menaged environments, you may want to check if a registry entry works better for this purpose. (We already have some PIN related stuff in `HKCU\\Software\\OpenSC Project\\OpenSC\\md_pinpad_dlg_enable_cancel`
- You may want to consider `sc_mem_secure_alloc()` for caching secrets.
- You may want to check if some of the other PINs can be used within the SM channel that was established via CAN. If so, you can possibly avoid re-validating CAN (and save around 1s in execution time)

2025-01-29 07:41 UTC, frankmorgner commented on src/libopensc/card-dtrust.c
> +	drv_data->can_value = can_env = getenv("DTRUST_CAN");
This buffer is not safe for later use. better use `getenv_s` or, at the very least, make a copy from the value.

2025-01-29 07:41 UTC, frankmorgner commented on src/libopensc/card-dtrust.c
> +	drv_data->can = 0;
I would prefer using NULL here

2025-01-29 07:41 UTC, frankmorgner commented on src/tools/dtrust-tool.c
> +		}
This is an endless loop, if the user always aborts the insertion of the PIN

2025-01-29 07:41 UTC, frankmorgner commented on src/tools/dtrust-tool.c
> +			/* FALLTHRU */
fall through

2025-01-29 07:41 UTC, frankmorgner commented on src/tools/dtrust-tool.c
> +			/* FALLTHRU */
fall through is recognized as well and it is gramatically correct

2025-01-29 07:41 UTC, frankmorgner commented on src/tools/dtrust-tool.c
> +			/* FALLTHRU */
fall through

2025-01-29 07:41 UTC, frankmorgner commented on src/tools/dtrust-tool.c
> +		 * and there is not next attempt. */
no next attempt?

2025-02-03 16:52 UTC, hamarituc commented on src/libopensc/card-dtrust.c
> +	drv_data->can = 0;
These are bit flags and not pointers. Are you sure to favor `NULL` here?

2025-02-03 16:52 UTC, hamarituc commented on src/tools/dtrust-tool.c
> +			/* FALLTHRU */
fixed

2025-02-03 16:52 UTC, hamarituc commented on src/tools/dtrust-tool.c
> +			/* FALLTHRU */
fixed

2025-02-03 16:52 UTC, hamarituc commented on src/tools/dtrust-tool.c
> +			/* FALLTHRU */
fixed

2025-02-03 16:52 UTC, hamarituc commented on src/tools/dtrust-tool.c
> +		 * and there is not next attempt. */
fixed

2025-02-03 16:55 UTC, hamarituc commented on src/libopensc/card-dtrust.c
> +	drv_data->can_value = can_env = getenv("DTRUST_CAN");
To be portable between Linux and Windows I decided to stay with `getenv()` here, but to copy the CAN value into a secure buffer. This also addresses your `sc_mem_secure_alloc()`-remark from above.

2025-02-03 16:59 UTC, hamarituc commented on src/tools/dtrust-tool.c
> +		}
This fail-operational pattern is intentional. When verifying the Transport PIN its use counter is set and cannot be used anymore. But the signature PIN still need to be changed. So whatever happens, the user should be prevented from accidentally aborting the program at this stage as it virtually bricks the card.

Nevertheless the user always has the possibility to abort the program by CTRL+C.

2025-02-03 17:05 UTC, hamarituc commented
> The code looks very promising. Apart from the comments above, here are some general suggestions:
> 
>     * Did you test caching of CAN in Windows Edge/IE? Last time I used this trick (I only have experience with IE), the browser was executed in a temporary user account, which had a different (temporary) home directory, which in turn is used by the PKCS#15 layer for caching files. I'm not sure if this security measure (?) is used by default or if it is triggered by some GPO, nor am I sure whether it is also used for Edge. When I ran into this problem I tied the caching directory to some path that was globally readable/writable. In less menaged environments, you may want to check if a registry entry works better for this purpose. (We already have some PIN related stuff in `HKCU\\Software\\OpenSC Project\\OpenSC\\md_pinpad_dlg_enable_cancel`

I didn't test with browsers, just document signing with Adobe and the command-line utils, of course. Can you provide a brief description what to test in the browser and how to do it?

>     * You may want to consider `sc_mem_secure_alloc()` for caching secrets.

Fixed.

>     * You may want to check if some of the other PINs can be used within the SM channel that was established via CAN. If so, you can possibly avoid re-validating CAN (and save around 1s in execution time)

I tested it for the PUK, but it could only be validated via PACE authentication not inside an already established PACE channel. I didn't test it for the Transport PIN as verifying the Transport PIN is only possible for one time. But the specifications states that only PACE authentication is supported for PUK and transport PINs and all my tests where consistent with that.

2025-02-10 09:41 UTC, frankmorgner commented
> Can you provide a brief description what to test in the browser and how to do it?

It's simple client authentication with a smart card certificate. If you do this with IE (Edge?), you should notice that the user cache files will not be written. Instead, you should find those files in an obscure filename which was created for a temporary user account. 

I believe using the registry as database for a saved CAN should be better in this case. Right now, I think you can leave it as is and consider this suggestion as improvement if you encounter any problems.

Thanks for having a look at the possibilities around using the PACE SM channel. I think there is no easy solution, but if the card is fast enough, it should not be a problem reevaluating some secret.

2025-05-26 19:36 UTC, hamarituc commented
> What's the status of this topic, is there anything to do?

From my point of view it's ready to merge. Just saving the CAN into the registry under windows is still an open topic I will solve in an other PR. Getting the driver for 5.1/5.4 cards into the master branch would be very gratifying as I already received the specs for the successor cards (expected to be issued in 2026) and would like start working on it.

2025-05-26 20:33 UTC, frankmorgner commented
OK, sounds great!

I'll have a look through the code soon. Please have a look at the build problems listed above.

2025-08-04 21:32 UTC, frankmorgner approved these changes

2025-08-12 11:47 UTC, Jakuje commented on src/libopensc/card-dtrust.c
>  // clang-format on
does this need to be enclosed with the `clang-format off`?

2025-08-12 13:43 UTC, hamarituc commented on src/libopensc/card-dtrust.c
>  // clang-format on
It's just for whitespace issues.

```
src/libopensc/card-dtrust.c:104:45: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp256r1 = {{ 1, 2, 840, 10045, 3, 1, 7, -1 }};
                                            ^
src/libopensc/card-dtrust.c:104:46: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp256r1 = {{ 1, 2, 840, 10045, 3, 1, 7, -1 }};
                                             ^
src/libopensc/card-dtrust.c:104:76: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp256r1 = {{ 1, 2, 840, 10045, 3, 1, 7, -1 }};
                                                                           ^
src/libopensc/card-dtrust.c:104:78: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp256r1 = {{ 1, 2, 840, 10045, 3, 1, 7, -1 }};
                                                                             ^
src/libopensc/card-dtrust.c:105:45: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp384r1 = {{ 1, 3, 132, 0, 34, -1 }};
                                            ^
src/libopensc/card-dtrust.c:105:46: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp384r1 = {{ 1, 3, 132, 0, 34, -1 }};
                                             ^
src/libopensc/card-dtrust.c:105:67: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp384r1 = {{ 1, 3, 132, 0, 34, -1 }};
                                                                  ^
src/libopensc/card-dtrust.c:105:69: warning: code should be clang-formatted [-Wclang-format-violations]
static struct sc_object_id oid_secp384r1 = {{ 1, 3, 132, 0, 34, -1 }};
```

I you prefer, I can remove the whitespace (and `clang-format` directives).

2025-08-12 14:10 UTC, Jakuje commented on src/libopensc/card-dtrust.c
>  // clang-format on
I would prefer to stick to the clang-format, unless it makes it significantly less readable. In this case, where it is just a whitespace inside of the quotes, I would prefer to use that rather than turning it off and on like this.

2025-08-13 11:07 UTC, hamarituc commented on src/libopensc/card-dtrust.c
>  // clang-format on
done

2025-08-13 14:28 UTC, Jakuje commented
Thank you! I think we are good to go. Merging then

2025-08-13 14:28 UTC, merged